name: Stock Scanner Full

on:
  schedule:
    - cron: '15 3 * * 1-5'   # 08:45 IST full fundamentals run (03:15 UTC)
    - cron: '0 * * * 1-5'    # hourly run (UTC) on weekdays
  workflow_dispatch:

jobs:
  scanner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Write Google credentials
        env:
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        run: |
          if [ -z "$GOOGLE_CREDENTIALS_JSON" ]; then
            echo "GOOGLE_CREDENTIALS_JSON secret missing"
            exit 1
          fi
          echo "$GOOGLE_CREDENTIALS_JSON" > credentials.json
      - name: Run scanner
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
        run: |
          python scanner.py
